# Site settings
title: Hao Liang
email: hliang21@outlook.com
description: 3nd year Computing student at Imperial College London # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
